services:
  tautulli:
    image: tautulli/tautulli:latest
    container_name: tautulli
    restart: unless-stopped
    ports:
      - "8181:8181"
    environment:
      - TZ=Asia/Kolkata
    volumes:
      - ./tautulli/config:/config
